
## Gopkg.toml example (these lines may be deleted)

## "required" lists a set of packages (not projects) that must be included in
## Gopkg.lock. This list is merged with the set of packages imported by the current
## project. Use it when your project needs a package it doesn't explicitly import -
## including "main" packages.
# required = ["github.com/user/thing/cmd/thing"]

## "ignored" lists a set of packages (not projects) that are ignored when
## dep statically analyzes source code. Ignored packages can be in this project,
## or in a dependency.
# ignored = ["github.com/user/project/badpkg"]

## Dependencies define constraints on dependent projects. They are respected by
## dep whether coming from the Gopkg.toml of the current project or a dependency.
# [[dependencies]]
## Required: the root import path of the project being constrained.
# name = "github.com/user/project"
#
## Recommended: the version constraint to enforce for the project.
## Only one of "branch", "version" or "revision" can be specified.
# version = "1.0.0"
# branch = "master"
# revision = "abc123"
#
## Optional: an alternate location (URL or import path) for the project's source.
# source = "https://github.com/myfork/package.git"

## Overrides have the same structure as [[dependencies]], but supercede all
## [[dependencies]] declarations from all projects. Only the current project's
## [[overrides]] are applied.
##
## Overrides are a sledgehammer. Use them only as a last resort.
# [[overrides]]
## Required: the root import path of the project being constrained.
# name = "github.com/user/project"
#
## Optional: specifying a version constraint override will cause all other
## constraints on this project to be ignored; only the overriden constraint
## need be satisfied.
## Again, only one of "branch", "version" or "revision" can be specified.
# version = "1.0.0"
# branch = "master"
# revision = "abc123"
#
## Optional: specifying an alternate source location as an override will
## enforce that the alternate location is used for that project, regardless of
## what source location any dependent projects specify.
# source = "https://github.com/myfork/package.git"


required = ["github.com/benbjohnson/tmpl","github.com/golang/protobuf/protoc-gen-go"]

[[dependencies]]
  name = "github.com/Azure/azure-sdk-for-go"
  revision = "bd73d950fa4440dae889bd9917bff7cef539f86e"

[[dependencies]]
  name = "github.com/Azure/go-autorest"
  revision = "8a25372bbfec739b8719a9e3987400d15ef9e179"

[[dependencies]]
  branch = "master"
  name = "github.com/davecgh/go-spew"

[[dependencies]]
  name = "github.com/eclipse/paho.mqtt.golang"
  version = "~1.0.0"

[[dependencies]]
  branch = "master"
  name = "github.com/evanphx/json-patch"

[[dependencies]]
  branch = "master"
  name = "github.com/ghodss/yaml"

[[dependencies]]
  branch = "master"
  name = "github.com/google/uuid"

[[dependencies]]
  name = "github.com/influxdata/influxdb"
  version = "~1.1.0"

[[dependencies]]
  branch = "master"
  name = "github.com/mitchellh/mapstructure"

[[dependencies]]
  branch = "logger-targetmanager-wait"
  name = "github.com/prometheus/prometheus"
  source = "github.com/goller/prometheus"

[[dependencies]]
  branch = "master"
  name = "github.com/shurcooL/markdownfmt"

[[overrides]]
  name = "github.com/Azure/azure-sdk-for-go"
  revision = "bd73d950fa4440dae889bd9917bff7cef539f86e"

[[overrides]]
  name = "github.com/Azure/go-autorest"
  revision = "8a25372bbfec739b8719a9e3987400d15ef9e179"

